BEGIN TRANSACTION;
CREATE DATABASE DB_CAMBIO (
CREATE TABLE TB_CAIXA (
idCaixa INTEGER PRIMARY KEY AUTOINCREMENT,
nomeCaixa VARCHAR(45) NOT NULL,
dataCaixa DATE NOT NULL,
cotaCaixa DECIMAL(5,2) NOT NULL,
dolaresCaixa DECIMAL(5,2) NOT NULL,
reaisCaixa DECIMAL(5,2) NOT NULL);
CREATE TABLE TB_TRANSACOES (
idTransacao INTEGER PRIMARY KEY AUTOINCREMENT,
TB_CAIXA_idCaixa INTEGER NOT NULL,
tipoTransacao VARCHAR(10) NOT NULL,
moedaTransacao VARCHAR(10) NOT NULL,
cotaTransacao DECIMAL(5,2) NOT NULL,
totalTransacao DECIMAL(5,2) NOT NULL,
FOREIGN KEY(TB_CAIXA_idCaixa) REFERENCES TB_CAIXA(idCaixa)););
COMMIT;
